version: 3
endpoint: http://localhost:8080
admin_secret: ALW4fsKJCfRuPMxgVFmqyAdEWXmP7yYFWVkgGj3dUvKJ9pG5BVcZMEkujKEpAXPY
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
